emb_dim: 300
lstm_units: 40
lstm_activation: 'tanh'
lstm_recurrent_activation: 'sigmoid'
lstm_dropout: 0.2
lstm_recurrent_dropout: 0.2
dense_activation: 'softmax'
batch_size: 1024
learning_rate: 1e-3
adam_beta_1: 0.9
adam_beta_2: 0.999
adam_epsilon: 1e-8